name: Manual Action Adding Tag

on:
  workflow_dispatch:
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test changelog
        run: |
          latestTag=$(git describe --tags --abbrev=0 --match int-*)
          currentCommit=$(git show HEAD --pretty=format:"%h" --no-patch)
          bash .github/scripts/changelog.sh $latestTag $currentCommit ABC