name: Manual Action

on:
  workflow_dispatch:
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test deployment
        run: |
          previousCommit=$(git show HEAD^1)
          echo $previousCommit
          echo ${{ github.sha }}
