name: Manual Action

on:
  workflow_dispatch:
    inputs:
      inputString:
        description: 'String input test'
        type: string
        required: false
      withTests:
        description: 'Should deployment be performed with tests?'
        type: boolean
        required: true
      environment:
        description: 'Deployment environment'
        type: environment
        required: true
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: boolean test
        if: ${{ inputs.withTests }}
        run: echo ${{ inputs.withTests }}
      - name: string test
        run: echo ${{ inputs.inputString }}
      - name: test deployment
        run: |
          previousCommit=$(git show HEAD^1)
          echo $previousCommit
          echo ${{ github.sha }}
