name: Manual Action Creating Changelog

on:
  workflow_dispatch:
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test changelog
        run: |
          latestTag=$(git describe --tags --abbrev=0 --match ind-*)
          currentCommit=$(git show HEAD --pretty=format:"%h" --no-patch)
          if [ -z $latestTag ]
          then
            bash .github/scripts/changelog.sh $latestTag $currentCommit ABC
          else
            echo ':: Changelog cannot be generated'
          fi