name: Manual Action Adding Tag

on:
  workflow_dispatch:
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test deployment
        run: |
          bash .github/scripts/tag.sh ina