name: Manual Action Creating Changelog

on:
  workflow_dispatch:
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    container: salesforce/salesforcedx:latest-slim
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test changelog
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if [ ! -z "$(git rev-list int-1..)" ]
          then
            latestTag=$(git describe --tags --abbrev=0 --match int-*)
            echo "latestTag=$latestTag" >> $GITHUB_ENV
            currentCommit=$(git show HEAD --pretty=format:"%h" --no-patch)
            bash .github/scripts/changelog.sh $latestTag $currentCommit ABC
          else
            echo ''
            echo ':::: Changelog cannot be generated'
          fi
      - name: test env variable
        run: |
          newLatestTagVariable=${{ env.latestTag }}
          if [[ ! -z "$newLatestTagVariable" ]]
          then
            path="force-app/tmp"
          else
            path="force-app"
          fi
          echo $path