name: Manual Action

on:
  workflow_dispatch:
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test deployment
        run: |
          variable=git show HEAD^1
          echo $variable
          echo ${{ github.sha }}
