name: Manual Action

on:
  workflow_dispatch:
    inputs:
      inputChoice:
        description: 'Choice input test'
        type: choice
        required: true
        options:
        - first
        - second
      withTests:
        description: 'Should deployment be performed with tests?'
        type: boolean
        required: true
        default: true
      environment:
        description: 'Deployment environment'
        type: environment
        required: true
      branches: main
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: boolean test
        if: ${{ inputs.withTests }}
        run: echo ${{ inputs.withTests }}
      - name: choice test
        run: echo ${{ inputs.inputChoice }}
      - name: test deployment
        run: |
          previousCommit=$(git show HEAD^1)
          echo $previousCommit
          echo ${{ github.sha }}
