name: PR Merged Automatic Deployment

on:
  pull_request:
    types: closed
    branches:
      - main
    paths:
      - 'test/**'
      
jobs:
  deployment:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: devkeydet/action-environment-queue@v1
        with:
          environment: int
      - name: build
        run: |
          echo "PR merged"
          sleep 2m
          echo "Test build after merge completed"
