name: PR validation

on:
  pull_request:
    branches: [ "main" ]
    
concurrency:
  group: validate-pr-${{ github.head_ref }}
  cancel-in-progress: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: devkeydet/action-environment-queue@v1
        with:
          environment: int

      # Runs a single command using the runners shell
      - name: Run echo merge base
        run: |
          currentBranch=$(git rev-parse --abbrev-ref HEAD)
          echo $currentBranch
          echo ${{ github.head_ref }}
          echo $(git diff origin/main...origin/${{ github.head_ref }} --name-only)

      # Runs a set of commands using the runners shell
      - name: Run failing multi-line script
        run: |
          echo Starting pr build
          echo ending pr build
