name: PR validation

on:
  pull_request:
    branches: [ "main" ]
    
concurrency:
  group: validate-pr-${{ github.head_ref }}
  cancel-in-progress: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: devkeydet/action-environment-queue@v1
        with:
          environment: int

      # Runs a single command using the runners shell
      - name: Run echo merge base
        run: |
          currentBranch=$(git rev-parse --abbrev-ref HEAD~1)
          echo ${GITHUB_REF##*/}
          echo $(git diff $currentBranch...main --name-only)

      # Runs a set of commands using the runners shell
      - name: Run failing multi-line script
        run: |
          echo Starting pr build
          bad step
          sleep 2m
          echo ending pr build
